import {
  Users, UserPlus, CalendarPlus, TrendingUp,
  DollarSign, Clock, CheckCircle, Receipt,
  BarChart3, Table2,
} from 'lucide-react'

export const WIDGET_CATEGORIES = [
  { key: 'kpis', label: 'KPIs', icon: TrendingUp },
  { key: 'charts', label: 'Graficos', icon: BarChart3 },
  { key: 'tables', label: 'Tablas', icon: Table2 },
]

export const WIDGET_CATALOG = {
  // ── KPIs (10) ─────────────────────────────────────────
  kpi_total_leads: {
    type: 'kpi_total_leads',
    label: 'Total leads',
    category: 'kpis',
    icon: Users,
    dataKey: 'total_leads',
    formato: 'number',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    roles: ['admin', 'director_ventas', 'setter'],
  },
  kpi_leads_hoy: {
    type: 'kpi_leads_hoy',
    label: 'Leads hoy',
    category: 'kpis',
    icon: UserPlus,
    dataKey: 'leads_hoy',
    formato: 'number',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    roles: ['admin', 'director_ventas', 'setter'],
  },
  kpi_leads_esta_semana: {
    type: 'kpi_leads_esta_semana',
    label: 'Leads esta semana',
    category: 'kpis',
    icon: CalendarPlus,
    dataKey: 'leads_esta_semana',
    formato: 'number',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    roles: ['admin', 'director_ventas', 'setter'],
  },
  kpi_leads_este_mes: {
    type: 'kpi_leads_este_mes',
    label: 'Leads este mes',
    category: 'kpis',
    icon: Users,
    dataKey: 'leads_este_mes',
    formato: 'number',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    roles: ['admin', 'director_ventas', 'setter'],
  },
  kpi_total_ventas: {
    type: 'kpi_total_ventas',
    label: 'Total ventas',
    category: 'kpis',
    icon: DollarSign,
    dataKey: 'total_ventas',
    formato: 'number',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    roles: ['admin', 'director_ventas', 'closer'],
  },
  kpi_ventas_pendientes: {
    type: 'kpi_ventas_pendientes',
    label: 'Ventas pendientes',
    category: 'kpis',
    icon: Clock,
    dataKey: 'ventas_pendientes',
    formato: 'number',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    roles: ['admin', 'director_ventas'],
  },
  kpi_ventas_aprobadas: {
    type: 'kpi_ventas_aprobadas',
    label: 'Ventas aprobadas',
    category: 'kpis',
    icon: CheckCircle,
    dataKey: 'ventas_aprobadas',
    formato: 'number',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    roles: ['admin', 'director_ventas', 'closer'],
  },
  kpi_ingresos_totales: {
    type: 'kpi_ingresos_totales',
    label: 'Ingresos totales',
    category: 'kpis',
    icon: DollarSign,
    dataKey: 'ingresos_totales',
    formato: 'currency',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    roles: ['admin', 'director_ventas', 'closer'],
  },
  kpi_ingresos_mes: {
    type: 'kpi_ingresos_mes',
    label: 'Ingresos este mes',
    category: 'kpis',
    icon: Receipt,
    dataKey: 'ingresos_mes',
    formato: 'currency',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    roles: ['admin', 'director_ventas', 'closer'],
  },
  kpi_ticket_medio: {
    type: 'kpi_ticket_medio',
    label: 'Ticket medio',
    category: 'kpis',
    icon: TrendingUp,
    dataKey: 'ticket_medio',
    formato: 'currency',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    roles: ['admin', 'director_ventas', 'closer'],
  },

  // ── Charts (2) ────────────────────────────────────────
  chart_leads_por_dia: {
    type: 'chart_leads_por_dia',
    label: 'Leads por dia',
    category: 'charts',
    icon: BarChart3,
    dataKey: 'leads_por_dia',
    chartType: 'line',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    roles: ['admin', 'director_ventas', 'setter'],
  },
  chart_ventas_por_dia: {
    type: 'chart_ventas_por_dia',
    label: 'Ventas por dia',
    category: 'charts',
    icon: BarChart3,
    dataKey: 'ventas_por_dia',
    chartType: 'line',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    roles: ['admin', 'director_ventas', 'closer'],
  },

  // ── Tables (2) ────────────────────────────────────────
  table_leads_recientes: {
    type: 'table_leads_recientes',
    label: 'Leads recientes',
    category: 'tables',
    icon: Table2,
    dataKey: 'leads_recientes',
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 3 },
    roles: ['admin', 'director_ventas', 'setter'],
  },
  table_ventas_recientes: {
    type: 'table_ventas_recientes',
    label: 'Ventas recientes',
    category: 'tables',
    icon: Table2,
    dataKey: 'ventas_recientes',
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 3 },
    roles: ['admin', 'director_ventas', 'closer'],
  },
}

export function getWidgetsForRole(rol) {
  return Object.fromEntries(
    Object.entries(WIDGET_CATALOG).filter(([, w]) => w.roles.includes(rol))
  )
}
